# yaml file to run the scripts and model experiments
transform:
    resize_dim: 256
    crop_dim: 224
train:
    shuffle_data: False
    batch_size: 128
    val_split_method: 'k-fold'
    k: 2
    val_percentage: 20
    loss: 'cross-entropy'
    epoch_interval: 1
    num_epochs: 5
model:
    name: 'resnet18'
    optimizer: 'Adam'
    lr: 0.001
    weight_decay: 0.00001
    amsgrad: False
    momentum: 0.9
test_model: False