# yaml file to run the scripts and model experiments
transform:
    resize_dim: 350
    crop_dim: 256
train:
    shuffle_data: False
    batch_size: 128
    val_split_method: 'fixed-split'
    k: 3
    val_percentage: 20
    loss: 'cross-entropy'
    epoch_interval: 1
    num_epochs: 2
model:
    name: 'alexnet'
    optimizer: 'Adam'
    lr: 0.001
    weight_decay: 0.00001
    amsgrad: False
    momentum: 0.9
test_model: False